version: "3.9"
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  spring-app:
    build: .
    restart: always
    environment:
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: db
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
